[theme]
primaryColor = "#4F8A8B"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#E9ECEF"
textColor = "#22223B"
font = "sans serif"
accentColor = "#FFB4A2"

# Optional: success and error colors for custom CSS
# successColor = "#43AA8B"
# errorColor = "#FF006E" 